### ISSUE TITLE
how redirect client to Mellat Payment Gateway

### ISSUE THREAD

**Issue by gohossein** [sinabakh/mellat-checkout#7]
after getting paymentRequest's response (RefId), how redirect the client to Payment Gateway?
IPG needs the client be redirected with the POST method, for REST API architecture how do that in client-side?
Is it possible for server-side to redirecting the client?

**Comment by sinabakh** [comment]
You should redirect the user to the following URL with post data `{RefId: YOUR_REF_ID }`:
https://bpm.shaparak.ir/pgwchannel/startpay.mellat
