### ISSUE TITLE
mellat bank never call redirect url on iphone 

### ISSUE THREAD

**Issue by alikianinejad** [sinabakh/mellat-checkout#8]
hi 
i am using your library to work with behpardakht and it is fine in web application and android devices but i have problem with IOS 
in iphone 8 every thing is fine but in iphone 6 and 7 redirect url never called by behpardakht but another apps (as i checked) work fine with behpardakht
please help if you have same problem ever 
behpardakht support Said nothing usefull

**Comment by sinabakh** [comment]
@alikianinejad 
Redirecting to the specified callback URL has nothing to do with this library and is handled by Behpardakht gateway, you may be able to find the problem in device logs (development mode in xCode).

ریدایرکت کردن یوزر بر عهده درگاه ملت می باشد و در نتیجه پشتیبانیشون باید پیگیری کند مشکل رو.
احتمالا میتونید ارور رو توی حالت دولوپمنت بررسی کنید.

**Comment by alikianinejad** [comment]
تنها جوابی که دادن این بود که مشکل از خودتونه
ولی بعد که بررسی کردم مشکل از اینجا بود که ریدایرکت از  بانک که اس اس ال هست به دامینی که اس اس ال نداره توسط سافاری جلوش گرفته میشه و باید حتما اس اس ال ست بشه 
با این مشکل حل شد ولی روی اندروید و وب و ورژن های جدیدتر سافاری مشکلی نداره

**Comment by sinabakh** [comment]
@alikianinejad خب به سلامتی خدا رو شکر که رفع شد.
